remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: The Empirical Skeptic
description: Random static generations on technology, information security, AI, pro-science skepticism, and futurism. 
