theme: jekyll-theme-minimal
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Empirical Skepticism 
description: Random static generations on technology, information security, AI, pro-science skepticism, and futurism. 
